CREATE TABLE payment (
     id BIGSERIAL PRIMARY KEY,
     studio_id BIGINT NOT NULL,
     member_id BIGINT NOT NULL,
     membership_id BIGINT,
     order_name VARCHAR(255) NOT NULL,
     amount BIGINT NOT NULL,
     method VARCHAR(30) NOT NULL,
     status VARCHAR(30) NOT NULL,
     membership_name VARCHAR(255) NOT NULL,
     membership_type VARCHAR(50) NOT NULL,
     membership_total_count INTEGER NOT NULL,
     membership_start_date DATE NOT NULL,
     membership_end_date DATE NOT NULL,
     paid_at TIMESTAMP,
     canceled_at TIMESTAMP,
     created_at TIMESTAMP NOT NULL,
     created_by BIGINT,
     updated_at TIMESTAMP NOT NULL,
     updated_by BIGINT
);