CREATE TABLE payment (
     id BIGSERIAL PRIMARY KEY,
     studio_id BIGINT NOT NULL,
     member_id BIGINT NOT NULL,
     membership_id BIGINT,
     order_name VARCHAR(255) NOT NULL,
     amount BIGINT NOT NULL,
     method VARCHAR(30) NOT NULL,
     status VARCHAR(30) NOT NULL,
     membership_name VARCHAR(255) NOT NULL,
     membership_type VARCHAR(50) NOT NULL,
     membership_total_count INTEGER NOT NULL,
     membership_start_date DATE NOT NULL,
     membership_end_date DATE NOT NULL,
     paid_at TIMESTAMP,
     canceled_at TIMESTAMP,
     pg_provider VARCHAR(50),
     pg_order_id VARCHAR(100),
     pg_payment_key VARCHAR(200),
     pg_raw_response TEXT,
     failed_reason VARCHAR(500),
     idempotency_key VARCHAR(100),
     created_at TIMESTAMP NOT NULL,
     created_by BIGINT,
     updated_at TIMESTAMP NOT NULL,
     updated_by BIGINT
);
